name: Build & Release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-action-node.yaml@fix/node-auth
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      node-version: '24'
