name: Build & Release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-action-node.yaml@8dc0aabd6d0cc4de62bb8fdfd4dbd9c6a923fd67 # v0.3.8
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      node-version: '24'
