name: Build & Release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-action-node.yaml@558b9ead422abd24faaa3d54b1735b3f14a67fc5 #v0.2.5
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      node-version: '24'
